"""Flow Matching policy for FPO (actor + critic).

Implements conditional flow matching:
  - The vector field v(x, t | obs) is parameterised by an MLP conditioned on
    observation and time t in [0, 1].
  - At inference, actions are generated by integrating x' = v(x, t | obs) from
    t=0 (Gaussian noise) to t=1 using a simple Euler solver.
  - Multiple action samples can be drawn per observation for the FPO update.

Reference: akanazawa/fpo gridworld/models
"""
import torch
import torch.nn as nn


def _build_mlp(input_dim: int, hidden_dims: list[int], activation: nn.Module):
    layers = []
    in_dim = input_dim
    for h in hidden_dims:
        layers += [nn.Linear(in_dim, h), activation]
        in_dim = h
    return nn.Sequential(*layers), in_dim


class FlowPolicy(nn.Module):
    """
    Actor-critic where the actor is a conditional flow matching network.

    Actor (vector field network):
        input:  [obs, x_t, t]  ->  hidden layers  ->  act_dim
    Critic (value network):
        input:  [obs]  ->  hidden layers  ->  1
    """

    def __init__(
        self,
        obs_dim: int,
        act_dim: int,
        hidden_dims: list[int],
        activation: str = "tanh",
        num_flow_samples: int = 8,
        flow_steps: int = 10,
    ):
        super().__init__()
        self.obs_dim = obs_dim
        self.act_dim = act_dim
        self.num_flow_samples = num_flow_samples
        self.flow_steps = flow_steps

        act_fn_actor = nn.Tanh() if activation == "tanh" else nn.ReLU()
        act_fn_critic = nn.Tanh() if activation == "tanh" else nn.ReLU()

        # Vector field network: obs + x_t + t -> act_dim
        vf_input_dim = obs_dim + act_dim + 1
        vf_backbone, vf_out = _build_mlp(vf_input_dim, hidden_dims, act_fn_actor)
        self.vf_backbone = vf_backbone
        self.vf_head = nn.Linear(vf_out, act_dim)

        # Critic: obs -> value
        critic_backbone, critic_out = _build_mlp(obs_dim, hidden_dims, act_fn_critic)
        self.critic_backbone = critic_backbone
        self.value_head = nn.Linear(critic_out, 1)

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.orthogonal_(m.weight, gain=1.0)
                nn.init.zeros_(m.bias)
        nn.init.orthogonal_(self.vf_head.weight, gain=0.01)
        nn.init.orthogonal_(self.value_head.weight, gain=1.0)

    def vector_field(self, obs: torch.Tensor, x: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        """
        Evaluate the conditional vector field v(x, t | obs).

        Args:
            obs: (B, obs_dim)
            x:   (B, act_dim)
            t:   (B, 1)  — scalar time in [0, 1]
        Returns:
            v:   (B, act_dim)
        """
        inp = torch.cat([obs, x, t], dim=-1)
        h = self.vf_backbone(inp)
        return self.vf_head(h)

    @torch.no_grad()
    def sample_actions(self, obs: torch.Tensor, num_samples: int | None = None) -> torch.Tensor:
        """
        Generate actions by integrating the flow from noise to t=1.

        Args:
            obs:         (B, obs_dim)
            num_samples: number of action samples per observation (default: self.num_flow_samples)
        Returns:
            actions:     (B, num_samples, act_dim)
        """
        K = num_samples or self.num_flow_samples
        B = obs.shape[0]

        # Repeat each obs K times: (B*K, obs_dim)
        obs_rep = obs.unsqueeze(1).expand(B, K, self.obs_dim).reshape(B * K, self.obs_dim)

        # Sample initial noise x_0 ~ N(0, I)
        x = torch.randn(B * K, self.act_dim, device=obs.device)

        dt = 1.0 / self.flow_steps
        for i in range(self.flow_steps):
            t_val = i / self.flow_steps
            t = torch.full((B * K, 1), t_val, device=obs.device)
            v = self.vector_field(obs_rep, x, t)
            x = x + dt * v

        return x.reshape(B, K, self.act_dim)

    def forward(self, obs: torch.Tensor):
        """
        Sample one action per env (for rollout collection) plus value estimate.

        Returns:
            action:   (B, act_dim)  — first of num_flow_samples
            log_prob: (B,)          — placeholder (0) used for ratio tracking
            value:    (B,)
        """
        actions = self.sample_actions(obs, num_samples=1)  # (B, 1, act_dim)
        action = actions[:, 0, :]  # (B, act_dim)

        value = self.value_head(self.critic_backbone(obs)).squeeze(-1)

        # FPO doesn't use per-step log_prob in the same way as PPO;
        # return zeros as placeholder for buffer compatibility.
        log_prob = torch.zeros(obs.shape[0], device=obs.device)

        return action, log_prob, value

    @torch.no_grad()
    def get_value(self, obs: torch.Tensor) -> torch.Tensor:
        return self.value_head(self.critic_backbone(obs)).squeeze(-1)

    @torch.no_grad()
    def sample_mc_pairs(
        self,
        obs: torch.Tensor,
        actions: torch.Tensor,
        n_mc: int,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Sample N_mc (τ, ε) pairs and compute the old-policy FPO loss sum.
        Called during rollout to cache data needed for the FPO ratio.

        Args:
            obs:     (B, obs_dim)
            actions: (B, act_dim)  — actions taken in the environment
            n_mc:    number of MC samples per action

        Returns:
            mc_taus:      (B, n_mc, 1)
            mc_epsilons:  (B, n_mc, act_dim)
            old_fpo_loss: (B,)  — sum of ℓ_θ over n_mc samples
        """
        B = obs.shape[0]
        mc_taus = torch.rand(B, n_mc, 1, device=obs.device)
        mc_epsilons = torch.randn(B, n_mc, self.act_dim, device=obs.device)

        # Flatten for vectorised vector-field evaluation
        obs_exp = obs.unsqueeze(1).expand(B, n_mc, self.obs_dim).reshape(B * n_mc, self.obs_dim)
        act_exp = actions.unsqueeze(1).expand(B, n_mc, self.act_dim).reshape(B * n_mc, self.act_dim)
        taus_flat = mc_taus.reshape(B * n_mc, 1)
        eps_flat = mc_epsilons.reshape(B * n_mc, self.act_dim)

        x_t = (1 - taus_flat) * eps_flat + taus_flat * act_exp
        target_v = act_exp - eps_flat
        pred_v = self.vector_field(obs_exp, x_t, taus_flat)

        # ℓ_θ(τ_i, ε_i) = mean over act_dim of squared error, then sum over n_mc
        per_sample = ((pred_v - target_v) ** 2).mean(dim=-1)   # (B*n_mc,)
        old_fpo_loss = per_sample.reshape(B, n_mc).sum(dim=1)  # (B,)

        return mc_taus, mc_epsilons, old_fpo_loss

    def compute_flow_loss(
        self,
        obs: torch.Tensor,
        actions_1: torch.Tensor,
    ) -> torch.Tensor:
        """
        Conditional flow matching loss (CFM).

        We train the vector field to match the straight-line path between
        x_0 ~ N(0,I) and x_1 (the target action):

            x_t = (1-t)*x_0 + t*x_1
            target_v = x_1 - x_0
            loss = ||v(x_t, t | obs) - target_v||^2

        Args:
            obs:       (B, act_dim)
            actions_1: (B, act_dim)  — target actions (e.g. sampled via policy gradient)
        """
        B = obs.shape[0]
        x_0 = torch.randn_like(actions_1)
        t = torch.rand(B, 1, device=obs.device)

        x_t = (1 - t) * x_0 + t * actions_1
        target_v = actions_1 - x_0

        pred_v = self.vector_field(obs, x_t, t)
        return ((pred_v - target_v) ** 2).mean()
